In [8]:
import numpy as np

'''
The following code is to help you play with Numpy, which is a library 
that provides functions that are especially useful when you have to
work with large arrays and matrices of numeric data, like doing 
matrix matrix multiplications. Also, Numpy is battle tested and 
optimized so that it runs fast, much faster than if you were working
with Python lists directly.
'''

'''
The array object class is the foundation of Numpy, and Numpy arrays are like
lists in Python, except that every thing inside an array must be of the
same type, like int or float.
'''

array = np.array([1, 4, 5, 8], float)
    
array
    




array([1., 4., 5., 8.])

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
    
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
'''
You can index, slice, and manipulate a Numpy array much like you would with a
a Python list.
'''

array = np.array([1, 4, 5, 8], float)

array
array[1]
array[:2]
array[1] = 5.0
array[1]


two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)

two_D_array
two_D_array[1][1]
two_D_array[1, :]
two_D_array[:, 2]


array([3., 6.])

In [13]:
'''
Here are some arithmetic operations that you can do with Numpy arrays
'''
# Change False to True to see Array arithmetics in action
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)

array_1 + array_2
array_1 - array_2
array_1 * array_2




array([ 5.,  4., 18.])

In [ ]:

'''
In addition to the standard arthimetic operations, Numpy also has a range of
other mathematical operations that you can apply to Numpy arrays, such as
mean and dot product.

Both of these functions will be useful in later programming quizzes.
'''

array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)

np.mean(array_1)
np.mean(array_2)
np.dot(array_1, array_2)